version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "src/Dockerfile_src"
  ]

test_patterns = [
  "test/**"
]

[[analyzers]]
name = "javascript"
