version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  plugins = ["react"]
  track_test_doc_coverage = true

[[transformers]]
name = "standardjs"
enabled = true
  