version = 1

test_patterns = [
  "**/tests/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  plugins = ["react"]

[[transformers]]
name = "standardjs"
enabled = true
  