version = 1

test_patterns = [
  "**/tests/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  plugins = ["react"]
  track_test_doc_coverage = false

[[transformers]]
name = "standardjs"
enabled = true
  