Object.prototype.hasOwnProperty.call(foo, 'bar')
({}.hasOwnProperty.call(foo, 'bar'))
foo.baz["isPrototypeOf"](bar)
foo.bar.baz["isPrototypeOf"](bar)

foo.hasOwnProperty('bar')
foo.isPrototypeOf(bar)
foo.propertyIsEnumerable(bar.baz)
foo.propertyIsEnumerable(bar())
foo.bar.hasOwnProperty(bar[baz])
foo.bar.baz.isPrototypeOf(bar['baz'])
foo.bar.baz.isPrototypeOf(bar)
foo[baz].isPrototypeOf(bar)
foo[baz].bar.isPrototypeOf(bar)
